#!/usr/bin/with-contenv bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 6555" \
    cd /opt/embystat s6-setuidgid abc /opt/embystat/EmbyStat \
        --data-dir /config \
        --log-dir /config/logs \
        --config-dir /config \
        --enable-updates false
